In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel('Данные для тестового задания.xlsx')

In [3]:
df

            date                               user_id  view_adverts
0     2023-11-11  8c020470-8461-11ed-83d0-552e8cc749d6            13
1     2023-11-18  5875f070-7b92-11ee-a6fb-8b298e83f4f7            14
2     2023-11-29  3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6            21
3     2023-11-29  234a96d0-ad16-11ed-a2e6-793ddfeeba1f            23
4     2023-11-29  4d07c180-644f-11eb-879c-b7c02edf4f37            12
...          ...                                   ...           ...
16809 2023-11-17  39df47d0-67e5-11ee-8fb4-6fca0b38dcdb             9
16810 2023-11-05  211ecf40-52f0-11ee-8000-aff5e9624248             9
16811 2023-11-16  ae274910-82d1-11ee-b2b8-1d1441fa3755             9
16812 2023-11-13  7b3d2810-e585-11ed-a524-d983167b6653             9
16813 2023-11-15  954bc9b0-5e75-11ed-b1a2-e10d23811e40             9

[16814 rows x 3 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16814 entries, 0 to 16813
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          16814 non-null  datetime64[ns]
 1   user_id       16814 non-null  object
 2   view_adverts  16814 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 394.2+ KB

In [5]:
#1
mau = df['user_id'].nunique()

In [6]:
mau

7639

In [9]:
df['Дата'] = pd.to_datetime(df['date'])
df['Месяц'] = df['date'].dt.to_period('M')

mau = df.groupby('Месяц')['user_id'].nunique()

In [10]:
mau

Месяц
2023-11    7639
Freq: M, Name: user_id, dtype: int64

In [11]:
#2
df['date'] = pd.to_datetime(df['date'])
dau = df.groupby('date')['user_id'].nunique()

In [12]:
dau

date
2023-11-01    623
2023-11-02    649
2023-11-03    573
2023-11-04    343
2023-11-05    350
2023-11-06    660
2023-11-07    629
2023-11-08    600
2023-11-09    661
2023-11-10    583
2023-11-11    354
2023-11-12    377
2023-11-13    646
2023-11-14    687
2023-11-15    690
2023-11-16    639
2023-11-17    585
2023-11-18    412
2023-11-19    378
2023-11-20    711
2023-11-21    651
2023-11-22    608
2023-11-23    632
2023-11-24    595
2023-11-25    366
2023-11-26    372
2023-11-27    589
2023-11-28    610
2023-11-29    621
2023-11-30    620
Name: user_id, dtype: int64

In [13]:
avg_dau = dau.mean()

In [14]:
avg_dau

np.float64(560.4666666666667)

In [20]:
#3
df['date'] = pd.to_datetime(df['date'])
first_day_users = df[df['date'] == '2023-11-01']['user_id'].unique()

In [21]:
first_day_users

array(['2f35ccf0-796b-11ed-96d9-2b24e5ad01fb',
       'ef6eb4d0-01bd-11ed-ab09-b1117ba72e2f',
       '17ce4000-77db-11ee-a3a0-edfd72e146b8',
       'd234f070-2821-11ed-9ce0-b7a9dd423e66',
       '77acbda0-786a-11ee-8810-032dc795ffb0',
       'f389d150-b7e6-11ed-8ad1-455c63298437',
       '3629cac0-721d-11ed-8fc7-4fd9990e1e38',
       '025a2b50-644b-11ea-97c8-0def17957c13',
       'd0924d40-1a32-11ee-b6e7-dd1694746746',
       'b102e250-b46b-11ed-9e46-b1e2925e9c5c',
       '17106bb0-b3d9-11ec-8539-4f93fa6e64e3',
       '6abb78c0-85d6-11ed-badb-fb3ca258c011',
       'ae900070-3a58-11ee-b03c-7ff923b46d35',
       '3a5bab80-269c-11e8-8319-456ad9d3b8d8',
       '0020a4c0-7402-11ee-b7d6-418bdd68d3fb',
       'b322ea40-33ae-11ee-8975-1dbaaffcfb54',
       '880f6dd0-416c-11ee-8820-d973c8eded16',
       '823fa620-6a63-11ee-a621-53985e61effe',
       '7c7c94e0-3cc4-11ee-adb1-11c8c9c6a31a',
       '64b239c0-e33f-11ed-9e8a-0720496d6e5a',
       'e91486b0-7899-11ee-ab9d-019e20babfc1',
       '2bb74140-0457-11ee-bd36-2f1e6e4a0d5b',
       'ad81b040-84a5-11eb-8d8c-4d18568caaf6',
       '71aa0370-bc01-11ed-b475-112ce88e695c',
       'ded85690-6f2f-11ee-90dc-d3739fe86b1a',
       'b78743e0-d902-11ec-b18a-f5d4e8e8e12e',
       '932d5ad0-781a-11ee-a0a8-e781fb8e2c8e',
       '390074a0-6b7c-11eb-8ef9-73f675c1c29c',
       '34061640-095f-11ec-8e63-4b3c41117f08',
       '32b3ba10-33a2-11eb-8aee-8751efd2dc63',
       '345d0fb0-5cee-11ee-a031-f9e6d8874212',
       '29e694b0-2e97-11ed-8dc3-3742abce6e54',
       '22761890-7473-11ee-aa2c-2b9644d64077',
       '2b3133e0-71dd-11ee-9549-b93ae01ac95e',
       'b4e62bb0-7244-11ee-b968-05e647b4bf8a',
       '5cc26300-1dc8-11eb-9164-7b820f8d19af',
       '429d9e50-04e2-11ee-b099-437be4de5b8b',
       'fa1f8e20-77fc-11ee-b1ef-2796fa3209b8',
       '3a3d4720-2aac-11ee-bfba-2511f1d20c67',
       '8a2ed430-2e10-11e9-8b85-733612b647ec',
       'b1c90ad0-9174-11ed-973f-d9c0d2c30895',
       'e95d9380-75ad-11ee-9778-df20dfde0e14',
       '678eeea0-51f2-11ee-84f0-539bab5a3b1e',
       '5ea51410-78d8-11ee-89a4-45397cf7c5ff',
       '21841810-49eb-11ec-b4da-2547bb8342c9',
       'ef609f50-0684-11ed-9ca0-f3eca5e64f25',
       '2a1af6e0-7849-11ee-8565-83473cd2ec91',
       'e9036980-78b6-11ee-8cae-03f7400cb400',
       '26625cc0-aa66-11ed-84e2-0fa7ce463de6',
       '2b44c810-78d1-11ee-94a0-53f52d76ff59',
       '0e7a9110-4b04-11ee-95ae-474bd0bb7789',
       'c7983f10-6fc8-11ee-bb29-8b2bc33f2226',
       '3d0629e0-d7fb-11ec-9cc6-892073864f49',
       '67a1c120-5886-11ee-b322-6bc629e3a519',
       'c42fd020-7862-11ee-af4a-ad0035b922d5',
       '81760d80-5522-11ed-9db6-4be11884d44f',
       'b931cd00-5e40-11ed-be59-cd8c375b0146',
       '9c8d4a30-4793-11e8-84c6-8defda07d6b5',
       '210c0300-b8ff-11ed-8f48-df00ad547483',
       'd7ceef40-78de-11ee-a914-a74061f438f8',
       '31a58880-7713-11ee-af51-ed76b53516cd',
       '5b421dc0-c7c0-11eb-9be8-cd2c10a60dba',
       '4096db10-ce2a-11ed-83f6-2f43771fa75d',
       '7e9b0220-3760-11ee-b6ab-e32a63927dfe',
       '036c87b0-267a-11e8-8408-f9f917206103',
       '55800e40-22d8-11ee-b4f4-a996d0a3653e',
       '3bd56d40-68bb-11ee-a940-1f6d25de55e9',
       'eba0aff0-48ae-11ee-abfb-cb003cc868e4',
       'e1626450-b689-11ed-9b96-7b01cb02c780',
       'ad037630-8edb-11ec-b14e-ad0027903dd7',
       'd94f0b00-4988-11ee-90cb-573c0fdfe79d',
       '22c0a340-69f8-11ee-aa39-ffc6a3d82012',
       'e7081680-b278-11ed-bc08-8d363ab79373',
       '9e63dfb0-73be-11ee-8d83-1f83326aad10',
       '2a872270-77d6-11ee-910f-8ffbb53dae26',
       '430f4dc0-0549-11eb-a833-2decc1b9312a',
       '639797f0-488a-11ee-be26-b1b10679e947',
       '0285c1b0-5db8-11ee-91a0-bd8641dc8912',
       'bbcb9de0-bc72-11ec-8bd3-b32104e0b6c3',
       '1522df20-78d8-11ee-8e7a-2f16e88e7c2d',
       '07cef780-de8e-11ed-b071-c587165c602b',
       '3ca7f550-09cd-11ee-a529-29a8549a386c',
       'e94b3f20-6345-11ee-9b1b-7985eb1a6cef',
       '014d1270-78c6-11ee-9871-6b58fdc2e5f3',
       '61ae0260-a6a2-11ed-8f7f-7df15ac93c97',
       '7cd29f20-b179-11ec-83d8-bba0166adfa6',
       '6ef3d460-7c3f-11ec-964a-4bc968753f25',
       'fb0db6c0-eed8-11ed-b021-df7a31580d1c',
       '8c1e2440-5ab8-11eb-9877-2f9b543fd058',
       '663c6800-0c17-11ee-926d-1ff95fc3e077',
       '8f256580-4ea0-11ed-9563-71e488ebc955',
       '537ccfb0-6a5f-11ee-83f9-3d79d5a1b56e',
       '7c4e4f20-757e-11ee-8d15-83cc13c1fe89',
       'd3fe4a80-9afb-11ed-b396-eb65577b605e',
       '9edeae80-61b6-11ee-9576-37fe3967ac3d',
       '6621abf0-5e88-11ee-842b-2bb3043f2c1c',
       '210ca360-55fc-11ee-915f-d9ba7fe6e9cf',
       '51ce6100-ab70-11ed-b691-65497f16113f',
       '6cb7f310-789c-11ee-82b0-ffa79938669b',
       '814a1740-7874-11ee-b748-69c3953bf89e',
       '533caae0-5438-11ed-a578-014dc2293f1a',
       'f2b8c6c0-fb73-11ed-94b8-cb6f0615e16b',
       '69611fd0-d414-11ec-bbd8-1d56831a1b7d',
       'f467ed90-6f07-11ee-abf5-49fc9b5925ab',
       '60355210-28de-11eb-aa02-c3649cfe7f71',
       '43717ff0-a3c5-11ed-ab92-2f5ca7d3e5b2',
       '1baaa8c0-4e0b-11ee-9a78-112355d65f25',
       '987a1860-043f-11e9-b29a-657a90787be9',
       '8c1900c0-18ff-11ee-b3c8-89750e6b01d2',
       'd29400a0-de44-11ec-b477-db56ab9d48af',
       '50573c90-9412-11ed-bab8-b5c12273e1c5',
       '475b1090-05f9-11ee-9467-d91149cad168',
       '342ab410-72f2-11ee-8510-a1d5dd7c7236',
       '11c6d7f0-6294-11ee-ba99-8303071649fa',
       'f09a5ce0-ec6d-11ea-87a9-ef965f094656',
       'd4021a30-2fd1-11eb-a413-8d939cea62b3',
       'db9dcc30-2d1c-11ee-bb57-6522ef6adb4c',
       'e64e9970-106a-11ea-a81f-2d486e26c435',
       '382484b0-4976-11ee-920e-2dc0028340f6',
       'e00bbcd0-2c9c-11ee-87a7-3f33b7dd19dd',
       'c511baf0-787e-11ee-aef1-bd36e0b6db35',
       '443cc080-214b-11ee-b198-4fddd179d52a',
       'c86d3510-cd63-11ed-9c56-1f05b1b09a2d',
       '1ce98380-dbc4-11ea-9602-c558fecff054',
       '62bfe730-6e8a-11ee-ac29-9f6e169b060e',
       '37346470-1ac6-11ec-98f9-e912f416724e',
       '639e9720-07ef-11ee-aba3-ad30eab8e8c6',
       '8a184340-2209-11ee-a8c7-3387bb4963c6',
       '52c20ae0-77f7-11ee-91ba-31fe468ba8b1',
       '3266df50-5b74-11ed-9db1-fb9122b43b4b',
       'ec0849f0-0e9b-11ee-baa6-4f692f343f0f',
       '442c4cd0-75ad-11ee-ba81-dfa01e423654',
       '97689660-7710-11ee-9dba-c74c763f95bb',
       '899fa370-78d2-11ee-899d-dbbda4db069d',
       '7f1b54f0-62be-11ee-9636-b1caf694bcd3',
       '995bb1b0-715b-11ee-9ac5-4b35b6b3dfb1',
       '31145bd0-ab4e-11ed-bd00-fdde66b73256',
       'c175b720-cbe5-11ed-bf77-d5b29ad6a156',
       'cd9be0a0-3f28-11ed-9329-1f955f70f5b6',
       'dee92d50-6b3b-11ee-ae38-b77b5e18d421',
       'ebaa7c30-761a-11ee-8629-cb6a2124c7c8',
       '6b848100-63f4-11ee-94c1-cd564f70789a',
       '28a70d20-916e-11ed-b4cc-134d52c5124a',
       'cbb2af70-a51a-11eb-bc9a-9b8287359b8f',
       'c230e1c0-5ae8-11ee-b386-5de8a6c82938',
       'c2f189a0-b335-11eb-8afe-8b116aff9ee9',
       '21a20810-76d6-11ee-8ad3-ff3e78388499',
       '61aa9be0-586b-11ee-9d78-ed8dd114beb7',
       '6863dc30-07ea-11ed-8e45-6d2618168de3',
       'c3e1c830-3452-11ed-b06b-6de81a8e026c',
       'e3f4b000-78bd-11ee-bf4e-d3f34681e1cc',
       'd7027f60-8a73-11ec-b5f2-c9a98f660e75',
       'c26d3200-5125-11ee-9a0f-c3816d7eb1e0',
       '483b6bd0-7873-11ee-a3d0-936034eff816',
       '11a82050-41ae-11ee-9175-7d03ae926415',
       '27bcbb20-5101-11ec-891e-9b7b6489f94e',
       '687339b0-549b-11ee-bae8-8b7a04a5bb59',
       '9a331d70-2b19-11eb-9436-8fbb00537f08',
       'edaf81b0-d76e-11ed-aa81-fd66fe9b4970',
       'd23a5fd0-55fa-11ee-a03c-139c780160bb',
       'd45f0c40-7290-11ee-a68d-a576871da231',
       '74b11f10-dcbc-11ec-a5f8-6db33301614a',
       '6d656ad0-24ce-11ee-98ae-69359935c18d',
       '97b80600-76fc-11ee-8a59-8bb6d8792ac3',
       'cbe265f0-6a64-11ee-8d8d-c1e74f246393',
       '07690c10-84d8-11ec-a5ec-659f78a8acae',
       '18554290-dfdd-11ec-bd0b-89a07386757e',
       '7048a140-e582-11ec-8d0e-f78e45bdf7d6',
       '08fcf6e0-9666-11ed-84be-0bae6b981ef0',
       'b36ee130-b266-11ed-98ae-6bcee419f29b',
       '3e1f96d0-f187-11ed-91d7-ff3d5e10e434',
       'c3dfc8e0-cf80-11ed-8508-2b894098691e',
       'c858e090-9098-11ed-b7e1-4120ad641f1d',
       '65b5b460-2c46-11e8-b433-e9a46e5ade44',
       '9e09a380-6651-11ee-bd22-5b15c10557df',
       'e7cfe960-2d45-11ee-bfbc-3f56c4d4fed8',
       'eb8c0040-c023-11e9-8c44-1bbbbcd7c7af',
       '28234cd0-52be-11ee-8438-dfcf34dc079c',
       'e9820b90-6a61-11ee-abcc-dd75dcdd7e70',
       '6e3654c0-02b3-11ee-b0ec-11f5491025c0',
       'b20e5d60-59fb-11e9-a0b4-a34c3e94afb5',
       '3699b490-45c9-11ee-b56d-ff5bebd6114d',
       'cf82ee70-5b80-11ee-af6f-a77ef701a079',
       '883a8720-e6a9-11ea-a364-0556a5a6c04f',
       'f6fa51f0-b720-11ed-bf6b-393d4015692c',
       '0f0edce0-9303-11ec-b86e-437588257343',
       '6e255e80-5ead-11ee-b9ab-514ff5ef01dc',
       '766fcff0-6795-11ec-bc56-dbe773a8e784',
       '5fa154d0-b4cc-11ed-b6bc-41f7c1a4f2bc',
       '4bf16490-38c4-11ed-b99c-3f068d13dd7e',
       '38f23a60-60d6-11ed-9055-050ecf74bb2a',
       'ec0b34c0-9a50-11ea-ab9b-5d80e3b25101',
       '5fef3740-5d00-11ee-9260-533e1e6323a4',
       '38855b10-9dc3-11ec-a5aa-b357fe13be33',
       'a4020350-4200-11ea-a3e3-0fa5ac2504b2',
       'a86e4c00-63b2-11e9-aa6c-3795c8f95f19',
       '9d377d60-1bc9-11ee-92b8-63e019d86f55',
       'eee45e90-931a-11ed-9d09-29c8fe6fce9a',
       'bafb8570-e353-11ed-9753-edccc786c976',
       '8ac758b0-8f71-11ed-93e2-bb1d349f94c8',
       '05520590-d607-11ed-9a94-c3117ae94577',
       'd64a01e0-7489-11ee-9ac9-edbcb318dc4f',
       '0c1031e0-e4a8-11ed-9e2b-e9731131cca2',
       'f34e3d80-359e-11ee-8ad1-7f56134b4302',
       '1a633e20-6745-11ee-ad73-95d1cc768655',
       '68bdc0a0-6bdb-11ee-ba47-8d3355969530',
       '14c64400-7887-11ee-9ade-1d96c494cf2d',
       '5edda700-85b6-11ed-89db-791595c6dafe',
       '5c996570-ad4c-11ed-ad4f-9748a31b1749',
       'd0480040-78d9-11ee-b864-57fcb53b99ea',
       '51fc4970-b951-11eb-b18b-e576f0c0802a',
       '1d6ca9d0-1b23-11ee-b179-ad7a8eb31bd1',
       'afe913b0-71c0-11ec-a39a-1d0894f5a843',
       '309dd140-586e-11ee-af5c-bb89e5600568',
       '4f860550-34f1-11ee-9908-0bcfb319b121',
       'c9912590-73bd-11ee-b124-edc22c6305b2',
       '154ae0b0-763f-11ee-86b9-7f40407285b5',
       'b37c6060-78c4-11ee-a880-c927841a2669',
       '130cc240-7889-11ee-aa17-571fcadf0394',
       '2418ed40-e322-11ed-a3c3-39019ef4fa21',
       '496e6520-3b8a-11ec-a905-2b5619b8e17c',
       '62d648d0-7276-11eb-a24e-3b66914edb0e',
       'c8e05f30-2408-11ee-92ec-59cbbcb06bf8',
       '28330160-2565-11ee-96b2-0b44ec9d8661',
       '17e3c5e0-f2d2-11ec-9a9d-15ce92c49139',
       '6ad1f470-e340-11ed-bfb0-5bf09b1451cd',
       '43a9bfc0-7483-11ee-af88-0be31bd14178',
       '2e44b9f0-6b91-11ee-b91c-c3ed2b3af3ac',
       '5bdf83b0-b21e-11eb-9904-bd2b81db69af',
       'b7e4d4b0-47c5-11ed-9239-2f1acd79db72',
       '747d6e10-101c-11ee-81f0-d7465ed299a3',
       '08ab2690-52d5-11ee-ba43-bd8cc8a1c62d',
       'f61308b0-78cf-11ee-a74e-894b0a9445e2',
       '616c5140-ffa8-11ec-8176-2b307e306f56',
       '98631cd0-27a9-11ea-a9a2-fdbc93cc1a8c',
       '3c07be10-ad51-11ed-9123-7986d83596a7',
       'dfbcb770-4958-11ed-a1f5-4f697baada95',
       '0176d5d0-eff3-11ed-8ea5-5f4c473eaf0a',
       '6d72db60-c723-11ed-9077-0bc5cf87e6be',
       'b91494a0-ee32-11e9-92c5-b7dd5733eb60',
       '9d3ef8a0-78a9-11ee-857c-0ba0c30c0672',
       '6c4f2840-4b1a-11e8-a39d-4907cd1dfe46',
       '5eb5dcc0-31e6-11ee-b425-f906d9714d16',
       '3816d050-5e83-11ee-b787-016174f78978',
       '6fce6c00-a610-11ed-a84b-a53c1c308f25',
       '8f868c50-5941-11ee-b38b-03e43b522cae',
       'a9703e70-55d3-11ee-b618-e36c12722ebe',
       '90626340-6717-11df-be47-03f2d32a026e',
       '665a2780-78a7-11ee-8865-f38ec601949a',
       '429c6650-c107-11eb-919c-2b8cd2bff7e9',
       'a4d16cb0-140e-11ee-8f85-05a7683ba1dc',
       '79d1b770-5bec-11ed-8c5d-91b880708635',
       '031b3f90-78c2-11ee-9e92-9952a86766f9',
       'c2052c90-5a95-11ee-8203-277b9b029b31',
       'd4ef4750-722d-11ee-93a0-0524a7eaba2b',
       '0bc4dd10-6736-11ee-b507-dbe0cfceb91c',
       'ee134c60-de9c-11ed-ade1-3f4e956f8c4b',
       '424d1220-63bd-11ee-bf5c-2915cf679904',
       '1375b1e0-2293-11ec-8d49-a77e871c2c65',
       'f67af260-7747-11ee-95b1-c90f48d8dcba',
       '46a2f740-78d0-11ee-a541-95266854a83d',
       '3e5fe530-78c0-11ee-914e-8fa7926522d5',
       '2c079400-5aa2-11ee-9d24-49e9e7fab6ba',
       '38d27c70-840a-11eb-a430-2f519e1f43ef',
       'd5556300-07fc-11ee-8250-117c7a6b7312',
       '3e8c9f50-32fd-11eb-9105-07ab860dcd0e',
       '508fdb90-4ae7-11ee-8372-c305d27f3c5b',
       '30873ef0-7875-11ed-b201-29b2b3a1b32c',
       'ddef2360-3147-11ee-9b78-edbe9e3bbef3',
       '424bb670-5138-11ed-98a8-1111c5b1bfed',
       'e2f4e540-7475-11ee-9392-217b8bd22c9e',
       '580b1600-5aeb-11ee-a31a-718c9cb74cd4',
       'db1ed730-78d6-11ee-bfda-1f3cf86c599d',
       '1cc131b0-7864-11ee-8c42-4574a3b89115',
       '17a208c0-6f3c-11ee-9819-87727da8d1de',
       '4a4b0cb0-f302-11ed-9814-e75cfbfa6ff7',
       'e2c41360-af2e-11ec-a79f-33c5a6212867',
       '3d8322f0-209e-11ee-bdb7-63a16ffb097c',
       '5b6e24c0-12e1-11ed-bb7a-819582b3bcb0',
       '349f69a0-78aa-11ee-b714-67a81852a666',
       '438855d0-67d7-11eb-ba32-55dcd093b535',
       '49511e60-5377-11ed-a8d3-1b23b22b81c8',
       'af44de40-1e82-11eb-ae0f-d74da888fa08',
       '2809fbe0-6cfe-11ee-9cf1-9f839b808b64',
       '11ead460-4bcf-11ee-a213-59f351ae2208',
       '074a8ca0-8da1-11ec-a4fe-2fe010861937',
       'c5212440-67c2-11e8-a4d6-f99da50c4b43',
       '93b5a860-5cb3-11ec-875b-5d452910b7a3',
       '7ec12bb0-3cda-11ee-9e53-d54ebe9dcd5b',
       '47d1d680-b5d1-11ed-819a-7fe655647e59',
       'bfb84fc0-b958-11eb-b3b5-714825858d67',
       'd78fa1e0-6ef9-11ed-886e-31f3a6be4046',
       '4f852cd0-d5ca-11eb-9d76-5923b3c29c12',
       '7aa0aad0-4589-11ee-8d7c-79491bd9f595',
       'f406dfa0-78bc-11ee-8a44-a7c6b5f1dbe2',
       'a5623b20-8eb0-11ed-aabd-01b51f03cf9b',
       '855400f0-78db-11ee-a1cc-0145671a8c27',
       'd1715f60-0929-11ec-acbc-63f9f7e9414c',
       'd7f98960-5921-11eb-a4ee-c17acd747435',
       'b776cdd0-6d03-11ee-b7d9-9fb72f14ae51',
       '6fa133d0-e250-11ed-a9ba-79b1e2ddbbf4',
       '18a80130-d909-11ed-8bb7-a722cfcf3c65',
       'b9e6c290-cd83-11eb-8c20-33f34c371fbf',
       '0c564110-2f3d-11e8-86fe-192b553f9733',
       '759c5b80-4d39-11ee-93e6-91fddc7b1be5',
       '45322020-68e0-11ee-af3c-951a4983eeee',
       'd3b12610-305f-11ea-82bc-2b8c7401f0aa',
       'a6be1be0-8ad7-11ea-87a7-d50c738ff5d1',
       '718e9310-6d04-11ee-a7ad-477a937c892e',
       '5b2423c0-9ca7-11ed-9a06-e98f8b1b1340',
       'cb080190-90c5-11ed-8cee-093727d167be',
       '0f1d7830-730e-11ee-b87c-ede2d6c21bc4',
       'ffedd7a0-79cc-11ed-9423-aba39d31dac6',
       '74ccfd80-5a32-11ee-8897-1d746f19b32a',
       'cdf179a0-7877-11ee-a52b-ab3bd49014ba',
       '1d0195b0-2789-11ee-a468-3bf96cf56455',
       'd98ef990-d454-11ec-b3f4-8913374e2678',
       '4caafbb0-b0d5-11ed-b29a-9588069690b5',
       '6a6959d0-ba19-11eb-aea6-7fbffab71459',
       '0a54b9f0-6a65-11ee-bf89-77b46f9d2e7f',
       'f7c42270-d75d-11ed-97f9-b9552bc26c77',
       '5549f370-eed4-11ec-844a-37590d323efc',
       '9d657c50-6965-11ec-a4a9-912dae094ad1',
       'c02e8000-fa1a-11ed-8794-dfffd14d7b5b',
       '7ca71aa0-e67d-11ed-b52f-730afe4cbf5d',
       'caa524f0-f3c9-11ed-85ac-3ddcab99fad3',
       '38d60640-78dd-11ee-b85f-ede3364fa3ef',
       'dc644e90-d6fb-11ed-ba63-c7c8945732db',
       '1842af20-76f2-11ed-a5ce-fdabccc41894',
       'ff847860-b685-11ec-988b-f7bc901f6613',
       '21631a50-3a7d-11ee-bf9d-87faf45ffb09',
       '265b0790-1782-11ec-9cf7-41818aa3fea0',
       '7934c600-6e1e-11ee-9e79-25f6a303b552',
       '4d02aee0-78d6-11ee-9502-f5f718d2dd79',
       '113a2350-78c4-11ee-bb50-b1a32fcee0fb',
       '1502bbd0-2bf6-11e8-8bb5-55e32622bfc9',
       'db0fa0d0-f875-11ed-b396-0f9c6f97c435',
       'cc413020-df2d-11ed-80e2-5b36f38ed607',
       'dedf85c0-18fc-11ee-a2bf-6de90bb26dfe',
       '29fc9ba0-16b0-11ee-a15b-f5d1bb5307e7',
       'f71ece30-7670-11ee-9c20-6978c11822de',
       '7b3d2810-e585-11ed-a524-d983167b6653',
       'd8157db0-2b95-11ea-880c-9179c07bc858',
       'd4634e60-c2e5-11ec-8d98-55a7b6fe357d',
       '62fe6b60-c708-11ed-8a74-cd53270ab4ca',
       'e6679ec0-2ebc-11e8-a277-534c066c029e',
       '6a9ba700-77d1-11ee-908d-37933b058941',
       '8d6d1370-3bfb-11ee-9242-7371dc682940',
       'c2aec470-9d63-11ed-b4c2-039bf3d2679a',
       'a12fd5c0-13d2-11ed-9577-2f98a8ff01ab',
       'b38d0c60-787b-11ee-a49d-6bcc0fb3408d',
       '674a6130-c95e-11ed-95df-cd96c90b3262',
       '73afa360-3fbe-11ed-9dc9-63ac06a28e1b',
       '9806cdb0-787a-11ee-b474-2bda9923664f',
       'b919eba0-ca20-11eb-b368-69bb43c71b4d',
       '7aa719a0-2556-11ed-ab15-ff21c970268c',
       '1d265690-099d-11ec-8c1f-279bde56d3d4',
       'c44efdd0-2bdd-11eb-a6a8-374e84e5cb57',
       'f8f17760-87fe-11ec-a736-1f2d4eb86998',
       '9a1bb5a0-2670-11e8-bfc6-df51f8419a76',
       '2b42c350-7870-11ee-906a-ff4f6dc8e252',
       'ffb13380-2454-11ee-a1d4-9d2cd639e536',
       '83dc6ec0-5dec-11ed-a7f8-43cd2dca137b',
       '8ff31860-6e4b-11ee-9196-0d7a410ed115',
       '42574c50-e4be-11ed-8be5-91dd0ec5cc9c',
       '20990ab0-78d2-11ee-9d50-99c7ce09dcd1',
       '6a9580e0-e359-11ec-919d-51f70cb7cc19',
       'cf669490-ff01-11ed-b4cf-75de7039d293',
       'c305d4a0-a915-11ed-94f7-d9cc05d27ce1',
       '821538d0-3b52-11ee-b76a-1d3a8edc4ac5',
       '1c4a5160-90e0-11ed-bb38-47496bab1f09',
       '719bc9c0-1ef5-11ee-a7f9-d504801ac8aa',
       '28bc4050-6031-11e8-9366-cb66763dc667',
       'cecce9a0-e1d6-11ed-9202-1122500419db',
       '5c5225c0-9870-11ed-ae85-019e14031a0e',
       'ad7c3ca0-4a55-11ee-af7f-751830de72d9',
       '10aafcf0-f6a9-11ec-9b0a-03fdc921c715',
       'd9eb4490-78a7-11ee-9467-d7beae77a559',
       '82d27e80-448b-11ee-90cd-538c962db324',
       'e4c75f50-b0f9-11ed-95d2-fb94d1b725d5',
       '0b7e3220-a8ff-11ed-ac6e-2b8b3b227614',
       '1c1578c0-1a27-11ee-bd88-2b897b20ac7e',
       'c53a4a90-31fe-11ee-902c-4bee995b2951',
       'c1a28c20-ba1f-11eb-98a9-ffa5882c14df',
       '6a1690d0-5227-11ee-b8ad-3f950449d99c',
       '608c91e0-3823-11ee-9189-2f1e9b840e31',
       'fbc98380-c324-11ed-8590-c540be38b137',
       'a66c38b0-786e-11ee-828b-bb07aba6dcff',
       'cd292dc0-1f77-11ec-8ccb-9167aa1054bc',
       '2c97c010-aa11-11ea-b260-43a005eb00ce',
       'd941c140-4b0c-11ee-b011-c3bac3a0b509',
       '72f5a3e0-65aa-11ed-85ab-e3e7268bebbb',
       '1da90f60-8d58-11ec-8446-41eb5caac821',
       '0d9ceaf0-c08e-11ed-9a72-5f01b56acec3',
       '31214450-2690-11e8-b8fd-0b549d32ed37',
       'b634cd60-12ad-11ee-a193-1938db7117be',
       'b5b65c40-9e46-11ed-9b7b-1fcfe56c7989',
       '2e592e30-7e75-11e8-99fe-877fced2befe',
       '0d570d00-9787-11eb-9da6-7b7c237064da',
       'aa2245d0-7e48-11eb-8a65-6b6b59b7d252',
       '69685390-1f9f-11ee-910f-157cf25f1d3b',
       '04b60840-0f21-11ee-9f41-590a8bddb14f',
       'dcd2d9e0-5465-11ee-a4e9-4b2d29c69e0e',
       '97eddc80-3df6-11ec-8968-315368755a67',
       '2c20c820-a586-11ed-b8df-fb8e4b5d1399',
       'b4d28780-046b-11eb-a7aa-2f3d29bb7930',
       '68871210-3b23-11ed-9944-954c1c93b64c',
       '62e0db40-41b9-11ea-a5ec-89523243447d',
       '519c0470-3acd-11ee-b387-d31d319de8e5',
       'c84a4520-7888-11ee-96c8-7b932d4317e1',
       'e9145e00-7688-11ee-8ef6-e111c86c784d',
       'e4f06660-4a60-11ee-961e-a56a262a73b7',
       '8b142ef0-0cf5-11ed-8af1-63871af601f1',
       '64b1f3c0-78bd-11ee-8c60-e906ec48acdb',
       'a3a3e0a0-13f7-11ee-bb1c-f95ada8d9aaf',
       '4614b480-d917-11ec-961d-e7ed5abf7e84',
       '67b556f0-7784-11ee-8349-8f4e44f9568f',
       '6b85a7f0-1bb6-11e9-b70b-bfa91045e908',
       '73148fd0-f075-11ec-bea2-dd8b958914a4',
       '2bbc0ee0-1fc4-11ee-aacf-4b00821eb4fb',
       '9af7be30-62a4-11ee-acd5-67c9b79d629a',
       '3690ea90-14af-11e9-a431-23c16d6fb172',
       '47e02010-dc6d-11ed-aa9f-cf7a03e8eb7b',
       '704fa250-c082-11ea-bb43-c1bfd3d804d5',
       '53180ba0-468a-11ee-9ac5-7bbaf6e4289a',

In [23]:
second_day_users = df[df['Дата'] == '2023-11-02']['user_id'].unique()

In [24]:
second_day_users

array(['b8b5b960-6653-11ee-9a79-2b363171d4bc',
       '302e5940-bcc0-11ed-bf87-9f2337527fae',
       '965ae8d0-7932-11ee-842a-c199ef6220e2',
       '90e084c0-56d5-11ee-82e7-095e0c88f0fd',
       'af142b30-4114-11ee-a7af-95b819bc48f9',
       '9bd30140-9ecb-11ed-a334-a32992c477f0',
       '3a84f7b0-793e-11ee-9714-61b81c09f753',
       '3629cac0-721d-11ed-8fc7-4fd9990e1e38',
       'b37c7bb0-4564-11ee-88c8-614141e4c1ed',
       'd234f070-2821-11ed-9ce0-b7a9dd423e66',
       '1a9bb300-8a6d-11e8-88cf-afe7d876fe57',
       'd7894be0-f1b4-11ed-a9ee-036e28b4d0c7',
       '33dbfb30-e046-11ec-8ffb-bf7cb75ce856',
       'd94e80e0-44c9-11ee-bd5d-df6656db5b76',
       'c26d3200-5125-11ee-9a0f-c3816d7eb1e0',
       '1a633e20-6745-11ee-ad73-95d1cc768655',
       'd3b12610-305f-11ea-82bc-2b8c7401f0aa',
       '8ce85230-7034-11ee-80e4-b1d3c171f6b4',
       '86e6e530-68f1-11ee-97c1-492d9f705dec',
       '28a70d20-916e-11ed-b4cc-134d52c5124a',
       'e1551310-7806-11ee-b76f-b98e5cf1cc76',
       'ec365110-57d4-11ee-99d9-eb3c2ad887bc',
       '537ccfb0-6a5f-11ee-83f9-3d79d5a1b56e',
       '27df59b0-7944-11ee-aca6-6dfa7952107b',
       'dec7c1b0-40a8-11ed-89c6-ff3d71f72346',
       'b919eba0-ca20-11eb-b368-69bb43c71b4d',
       '7858d880-78e0-11ee-a3eb-5532c009ed96',
       '116a88d0-6652-11ee-8cdf-41dd3c90c1f6',
       '904969c0-5db8-11ee-9185-e5270066a2d3',
       '0322c400-00fd-11ee-9914-013d585dacc5',
       'd4b93fd0-0427-11ee-8986-f30e6b4525b4',
       'c41758c0-9a7c-11ed-96f8-85c276d49420',
       '59929b90-f8ed-11eb-be6a-bdaca425bea2',
       '3f6e2310-e8c4-11ed-92ad-e71197dd3386',
       '2603ef60-fe34-11ed-910f-ed4de5f486e7',
       'fd5c08a0-614c-11ee-9ce0-e14fc61820da',
       '75c3c8a0-c3dc-11ed-a151-3b61a6600a95',
       '498f84e0-4875-11ee-8abc-61aeb8e0334b',
       'd4b53460-61ee-11ee-bb08-93062146ca1c',
       'bf03a510-7991-11ee-8852-2143de4f27e0',
       '24f11e50-17e7-11ee-a4c0-17499c05ef16',
       'a6e09ac0-7931-11ee-8723-2b8936b904e6',
       'afe913b0-71c0-11ec-a39a-1d0894f5a843',
       '4837af70-77bc-11ee-b28d-df143479094c',
       'ee4fd9c0-b57e-11ec-8ef1-e763c87d7838',
       '50787e40-6cad-11ee-b59e-99b651d6956d',
       'c47353d0-6f85-11ee-bb06-a943307bf4aa',
       '85e45500-e972-11ec-9be0-1dac9f70c8fe',
       '7ebd9730-2a83-11ed-a8ba-89d358137e29',
       '37ca6ba0-431f-11e8-8a1d-b37352c63da2',
       '6cb03670-a90d-11ed-8767-1b1ff1f36ee4',
       '81612e50-7690-11eb-80da-c9831175f4e0',
       '442d7f60-4baa-11ee-91f0-ff776ff13f6f',
       'fc4a9d50-d74f-11ed-9cdd-25ff3d1aa535',
       '80fe6d00-f9e8-11ed-9b52-97f77575679a',
       'b530a5b0-7838-11ee-bb5f-41944d1bdb5a',
       '1c4a5160-90e0-11ed-bb38-47496bab1f09',
       '9b67b320-5a54-11ec-a9df-2fb8bf00ad6e',
       'bf395920-debb-11ec-9d13-bd991bc9510d',
       '1a1fed60-0a9c-11ee-bf62-9d52c515203b',
       'c031b040-6676-11ee-8b14-0bf74ef12335',
       'afcf63d0-acf6-11ed-862e-d53056731300',
       '5fe8ad10-ed55-11ec-aeef-7755fe139428',
       '704fa250-c082-11ea-bb43-c1bfd3d804d5',
       '8ba2ae90-9be6-11eb-9d8f-4f71aa2d7fda',
       '3a8f0e30-795c-11ee-b7a3-61a78c2da200',
       'd0b5b640-7815-11ee-ba60-d55fcf62803c',
       '028805a0-908d-11ec-9f37-27c651076562',
       '85e35260-67f5-11ee-a399-419e1c537f6f',
       '6007dd90-74f1-11ea-9415-f927bf30edd6',
       'aa6ebcf0-5094-11ee-913d-f168a1c498b5',
       '02f49200-afb7-11ea-8eda-05d78e841563',
       '17e3c5e0-f2d2-11ec-9a9d-15ce92c49139',
       'e00bbcd0-2c9c-11ee-87a7-3f33b7dd19dd',
       '431812d0-5c34-11ee-8cfb-cd8178d75236',
       '11c6d7f0-6294-11ee-ba99-8303071649fa',
       'bc6151c0-266f-11e8-82f3-01b53ba05a21',
       '76b7b5e0-3a71-11ed-a8de-d1ecc1a6e4c3',
       'a5955ba0-7969-11ee-a09d-174fbdbba10d',
       '938550a0-60dd-11ed-94d2-0958f9e80160',
       'd9a53120-5648-11ee-a608-0d3249132a5e',
       'caa524f0-f3c9-11ed-85ac-3ddcab99fad3',
       '2630a7f0-3a7d-11ee-88b2-d18fd7859087',
       '47d1d680-b5d1-11ed-819a-7fe655647e59',
       '8c5f8420-793d-11ee-a05e-1f149c98de13',
       '68e7b470-79f4-11ed-b1d2-e94a444046b6',
       '5f2afc00-78cf-11ee-b854-b99a46e8257e',
       '616c5140-ffa8-11ec-8176-2b307e306f56',
       '2295f300-206c-11e9-b70d-d917d1c83c15',
       '33f92100-26d3-11e8-aaf0-43521b84df22',
       'cbb2af70-a51a-11eb-bc9a-9b8287359b8f',
       '6fc09df0-634d-11ee-805e-c136d87517a5',
       '9a0f4460-a9a2-11eb-be82-75b0b9b423a9',
       '97eddc80-3df6-11ec-8968-315368755a67',
       '9d71bc10-78e3-11ee-af92-7751fd48aad1',
       '02a6a090-6652-11ee-9586-e5eb3b3de661',
       'b8800af0-6dc8-11ee-8ada-c7d2dc4bb73d',
       'fa04c580-9d85-11eb-b366-5bf28c116536',
       '03730d20-5ce2-11ee-9006-b178b960a5f1',
       '364354f0-e4d6-11ed-857b-f11dd0dac507',
       '21ca72e0-5dab-11ed-b3ec-4f4a0fa1ccfa',
       '5c39cfb0-6f30-11ee-9629-9fc102588c71',
       '68375db0-fba4-11ec-97bd-39471ab4cafe',
       '0b7e3220-a8ff-11ed-ac6e-2b8b3b227614',
       'a262d200-baf2-11ec-8f5a-77dc8568248f',
       '9496d8f0-79a6-11ee-a7db-ad63a3819194',
       'e8bada70-7948-11ee-964e-4b8e9861785c',
       '73b8a040-c069-11ea-8f6e-73b4bc9df9ed',
       '438855d0-67d7-11eb-ba32-55dcd093b535',
       '0b8e2e10-793c-11ee-8186-7b75ac76f8f0',
       '0c5918f0-35c1-11ee-bebd-bfdf2d080bd2',
       'da1815a0-5a6d-11ed-af94-b9d8efa558d7',
       'd3510020-254b-11ee-841e-3590bf2ce428',
       '1cd40f00-26d1-11e8-aed5-87569c2029e9',
       '306dcee0-232c-11ee-a598-f9a8cc7e64b6',
       'bac083b0-f0ad-11ec-aee7-9d8b613f08bd',
       '46eabd50-5eb3-11ee-974c-df6d395297d3',
       'de80ed50-792b-11ee-b06f-7db8f92754ce',
       '8b142ef0-0cf5-11ed-8af1-63871af601f1',
       '1d474e40-2a76-11e8-8518-17b20fa8751f',
       'a4db9460-d7f3-11ea-a881-d576d1a06d25',
       '9e227cf0-749a-11ee-9314-2dc95b8464b6',
       '3c07be10-ad51-11ed-9123-7986d83596a7',
       '8cd83050-f8b9-11ed-b53e-8df4350d6ab8',
       '802e4a00-46cd-11ec-b182-0123b788ccc1',
       '34ed9ad0-f920-11ed-9355-b763fe34d06a',
       'f7c16bf0-448d-11ee-9152-5d2cf8d23c8d',
       'b9a2da30-78b7-11ee-87b5-ef8e019bcd1c',
       'ce5574e0-680b-11ee-a86c-ef9cd1d092e9',
       '8e56c270-fe2f-11ea-b081-afd3e019753e',
       'd92ce3b0-f52b-11ed-9532-9fb2bd6a5840',
       'adafa7c0-55d1-11ee-940b-d1474356896c',
       '67b22b80-7156-11ee-9c2f-59c580af0bd3',
       '7eef3ef0-61d9-11ee-b559-558d51579912',
       'e64e9970-106a-11ea-a81f-2d486e26c435',
       '6cb3f870-7ad5-11ed-be43-f13be62b8eb5',
       'aac97a60-9910-11ec-9271-0d32e5e37ef4',
       'bfb1b590-4dd9-11ed-84ed-6baa0af96a39',
       'e69b27f0-bfd5-11ec-8e5c-3f78e8b19bd7',
       '02a1d900-a64c-11ed-a3c5-4da84c18504e',
       '5af80cb0-69a5-11ee-90c2-6bf305645d5a',
       '74cb35f0-7985-11ee-a2a3-a3cdefd12b91',
       'e9820b90-6a61-11ee-abcc-dd75dcdd7e70',
       '5a2cf4e0-6b55-11eb-9b89-6d74871a290e',
       '954b63b0-7929-11ee-b848-5d624d9bb4d2',
       'c2bb7050-c085-11ec-a6d6-05fa39c0b5d0',
       'c5c77150-ff67-11ed-9478-ebe39a40465c',
       '90dd5bb0-78f8-11ea-a303-d76acc5d7fdd',
       'b728cf30-6be2-11ee-9a54-2709e5f9b078',
       'f5c917b0-19f6-11ee-9ff9-bb2aeb994a1d',
       'e2c41360-af2e-11ec-a79f-33c5a6212867',
       '6716d230-26e1-11ee-8726-d5b75c527547',
       '3a04c150-214d-11ea-b5fe-69726f78d9f0',
       'b2a21c20-a872-11ed-a9aa-9567fc592108',
       '0c1031e0-e4a8-11ed-9e2b-e9731131cca2',
       '4208b140-9cab-11ed-bb7f-d190274d81fd',
       'a214e7a0-6fca-11ee-bb4c-5bc1dc6040cc',
       '5d120860-d482-11e8-84cb-3b32700906f9',
       '498288e0-7812-11ee-bd13-cd3f2081c40a',
       '592c5940-794f-11ee-b979-33685d1540d8',
       'efde7d10-5718-11ec-a041-51d9445c296e',
       '681dbe10-85c3-11ed-bb97-25ca7a3d089c',
       '2611bf40-6343-11ee-a3fd-6fead0b45f92',
       '074c1180-b15e-11eb-b066-a5e5e9193957',
       '429c6650-c107-11eb-919c-2b8cd2bff7e9',
       '8c399da0-5061-11ee-b86b-773a560c470e',
       'f6bc3bd0-78e1-11ee-8308-83044dda16dd',
       'ba0b4520-080a-11ee-b26f-356151662bfe',
       '973ddf10-30ad-11e8-94b5-05fb3f125577',
       'fae8adc0-6ede-11eb-9e19-47088db49aac',
       '94a2aec0-fc31-11ed-bf4b-237299cb29b4',
       'dc644e90-d6fb-11ed-ba63-c7c8945732db',
       '5807f950-7956-11ee-87c1-77433193f297',
       'd7660620-5e6c-11ed-b4ca-9fd1b2002159',
       '32a76e40-1296-11eb-ad8e-b1739a1071e3',
       '90010330-5b54-11ee-af0d-a124f8839517',
       '6c3b5da0-57ae-11ee-8354-d77ee1a0b9a0',
       '90626340-6717-11df-be47-03f2d32a026e',
       '17610930-58cf-11e8-bc52-fbc4499d07ad',
       '71a08180-7946-11ee-862f-7909d44ee27c',
       '1f3af260-78b3-11ee-a522-ff1782f7f043',
       'fd3e2930-34d2-11ee-9756-f99b05777bbd',
       '6d656ad0-24ce-11ee-98ae-69359935c18d',
       '9c8b8a50-7531-11eb-9d56-ad5d73c2050d',
       '130cc240-7889-11ee-aa17-571fcadf0394',
       '64b239c0-e33f-11ed-9e8a-0720496d6e5a',
       'ebac4fc0-d9c0-11ed-afd0-f3184bbdad64',
       'c2326450-7924-11ee-98f0-a3fe2bd3934b',
       '3c9a6500-1efb-11ee-8136-c7632e12c8ef',
       '939dbdb0-f6fd-11ec-a9ab-b342f56aca2d',
       'e0debd00-7937-11ee-9671-65f7e19d7a35',
       'ddef2360-3147-11ee-9b78-edbe9e3bbef3',
       'a12fd5c0-13d2-11ed-9577-2f98a8ff01ab',
       '65f0d690-af35-11e8-928d-3d9e5d054343',
       '1f1f4fa0-4af6-11ee-aa62-e1dbc486b74e',
       'a58e0640-681e-11ee-ad34-9bdaba20fadd',
       'afd82fd0-ab69-11ed-bff9-c95875bd4134',
       '48bcb760-1fab-11ee-8e03-1f28c22350fa',
       'e95d9380-75ad-11ee-9778-df20dfde0e14',
       '18554290-dfdd-11ec-bd0b-89a07386757e',
       '7d2cf490-5d4b-11ea-a6da-6907c0265f74',
       '4d488370-5ce8-11ee-a1cc-9dc5cd4b1d41',
       'a0ff83c0-5080-11ee-9c59-f71f0115f9cb',
       'ad4d4aa0-3f0a-11ed-af31-69baa8086303',
       'f3b05090-6386-11ee-b738-411998dddbba',
       'bf07d300-a3e6-11ed-bcd5-cf87783ff67e',
       'bb052f80-62a1-11ee-9092-7d41a6e6fb27',
       'ea6d81d0-78ab-11ee-aac8-61ef4ba0b1e5',
       '5f993750-683a-11ea-96c5-0b4aa9599a94',
       '3a8fc3b0-557c-11ee-9343-b31e3ab30159',
       '390074a0-6b7c-11eb-8ef9-73f675c1c29c',
       '1e8729b0-cc2a-11ec-8b8e-c93ce2ec9f49',
       'c43859a0-2576-11ee-95c0-f3a8eb36e260',
       '4952ccf0-6664-11ee-a2b2-85769fefe3a1',
       '44e7a6f0-6b75-11eb-81b9-e13b91a3882f',
       'ce47a670-6690-11ee-936f-d7ea40ba2527',
       'd98ef990-d454-11ec-b3f4-8913374e2678',
       '37a0fa50-792d-11ee-939f-73226e7ce2f6',
       'f21e22d0-567f-11ed-ab53-0db2be12f6a3',
       '74981b70-6a44-11ee-a84a-35f93377f286',
       '55dd0b50-b8d4-11ec-a5cf-6ff7cfa0bdc8',
       'b87a5e00-d22a-11ed-8dbd-abd3c172a8b4',
       '42f42970-cf90-11eb-a6b8-5986bf59c517',
       'b8e32e40-c24d-11ed-a3cc-074b079cf1a2',
       '30873ef0-7875-11ed-b201-29b2b3a1b32c',
       '62228ff0-7162-11ee-81a4-6b01e1b48ba8',
       '58bacd60-6343-11ee-910a-219bf466f77b',
       '81e227d0-6779-11ee-879f-d915a676ae6b',
       'eb132880-3740-11ee-8c07-71390b0dbaa0',
       '68342f10-6d6c-11ee-839a-d33a23a1417a',
       '564ccfd0-bf9c-11eb-982c-d7692f1f341c',
       'ff52b590-2297-11ed-8cb9-e5dc54b353b6',
       'aa9b5be0-6f95-11ea-bd4f-81608d74ea67',
       'c858e090-9098-11ed-b7e1-4120ad641f1d',
       '48ec9dd0-6192-11ee-94f1-0560d41158cd',
       '0e7a9110-4b04-11ee-95ae-474bd0bb7789',
       '79bedff0-4ffb-11eb-af7c-350316180a48',
       '4b547460-beca-11ec-a13d-17d32a060020',
       '369bb660-627a-11ed-9783-415677af7f4a',
       '4e611980-fc6b-11ed-a573-0f4ac03065a8',
       '76175a70-1942-11eb-8775-d35d90aec7ae',
       'b125c000-3e49-11ee-9bab-ddd0cf04084f',
       '8aca5ab0-4c2d-11ed-ba4f-3339b0969613',
       'dc226c30-5c95-11ee-91f1-dbedbfd3f6af',
       'b210bc50-a35d-11ec-9131-69cf4237b2c9',
       'a07707d0-42b2-11ec-95ea-0bc5636e7c1e',
       '74c02120-797f-11ee-8929-b310d0e1b4db',
       '00004230-d665-11eb-b2d7-a15ffd6a3364',
       '62bfe730-6e8a-11ee-ac29-9f6e169b060e',
       'b19133d0-626b-11ee-865a-434320643fe9',
       '1424a0d0-769a-11ee-b418-251a21c0ad9b',
       'dbd61a00-4b07-11ee-b573-f767a437ff98',
       '6d9fa570-6cdf-11ee-98be-fb02a8e8b4e2',
       '5f53de40-d41f-11ed-abc9-e395eb253d81',
       '301db200-796e-11ee-8fa3-632ed048cb9d',
       'd78fa1e0-6ef9-11ed-886e-31f3a6be4046',
       'bd60de30-970b-11ed-93bb-ffee1c050103',
       '4a728d80-5b86-11ed-a4ce-7741a3242207',
       '9f9a7140-5f3f-11ec-a4b6-cbf13489682a',
       'c120e7f0-795e-11ee-a827-0912c2b03dc2',
       '2ca4dc30-1748-11ee-8f40-e19906ae1db2',
       'ce0d5010-d847-11ed-be3e-4f187091f243',
       '93209f90-7999-11ee-ab55-31a07f609c4a',
       '94156890-272e-11e8-92c5-1f8025567be4',
       '766e3c50-a315-11ed-ada7-53bfc1cd2ab7',
       '0176d5d0-eff3-11ed-8ea5-5f4c473eaf0a',
       'ff847860-b685-11ec-988b-f7bc901f6613',
       'a351bde0-77a0-11ee-8fdc-0d808d1c8e09',
       'eb1b9300-5b8d-11e9-bc07-057b2d70c393',
       '4b065740-f8b1-11ed-a0ea-43015548e4d6',
       '6261b740-7872-11ee-961f-5517ccf7abcc',
       'f67af260-7747-11ee-95b1-c90f48d8dcba',
       '5ee9ed60-8222-11eb-80f0-159aa0597eff',
       'bafb8570-e353-11ed-9753-edccc786c976',
       'cbe265f0-6a64-11ee-8d8d-c1e74f246393',
       '06156c60-564a-11ee-9e42-b3913ca46edc',
       'ded85690-6f2f-11ee-90dc-d3739fe86b1a',
       '28850880-1854-11ed-a7a1-919bf16229cf',
       '580b1600-5aeb-11ee-a31a-718c9cb74cd4',
       '29e694b0-2e97-11ed-8dc3-3742abce6e54',
       '2cd32690-4bea-11ee-9e49-4306092a325a',
       'b322ea40-33ae-11ee-8975-1dbaaffcfb54',
       'b2b1e200-7954-11ee-bc71-894072e2c897',
       '17ef2390-d33f-11ea-8923-e9987a7d3c58',
       'c230e1c0-5ae8-11ee-b386-5de8a6c82938',
       '13c4fbd0-78e3-11ee-8a52-0f7a2f74480f',
       '2a9830c0-60dd-11ee-8c2d-db58d921319b',
       '2418ed40-e322-11ed-a3c3-39019ef4fa21',
       '974047e0-52b3-11ee-8f8b-23b9d0977d42',
       'daac7c40-7155-11ee-9e85-fbbf994bb97a',
       '71d9c8b0-b7af-11eb-b51d-ab034141f9a1',
       '1d48b790-786c-11ee-8f2e-5789dd3d51d3',
       '1dca2ef0-21cb-11ec-885e-6703ed07e631',
       '016cbf40-3766-11ee-99a4-8d5a4f083920',
       '6c493400-7952-11ee-aae3-5914b6228ab4',
       '070cfa10-78ec-11ee-ac9a-7bcf3cd1fb3e',
       'da33a030-513f-11ee-818d-2b8f59562586',
       'c0851320-fad8-11ed-8bb9-5793d27ec8d2',
       '3f35b8e0-101f-11ee-82db-d9eb8e0d664b',
       '54e54190-6bd9-11ee-8f34-7501bfd988a8',
       '7422d5f0-4559-11ee-8887-55aa3a8ef55d',
       '80a33bf0-280d-11ec-8a50-d357e2855c5a',
       'c7cac260-42c4-11ec-a18d-c59760f8617f',
       '8c1900c0-18ff-11ee-b3c8-89750e6b01d2',
       '8c81def0-0411-11ed-99fa-3722f70332f6',
       '85bc2b20-a377-11ec-8ee2-0912cae8416b',
       'ee9adb30-f9e0-11ed-8393-433a3d955e51',
       'f37fc460-de32-11eb-8054-3fb03dcea04c',
       '05290bf0-fe8e-11ec-a077-47257edb8e0e',
       'f500b590-c06f-11ec-8b2f-e9f5deb0405e',
       'bd27f410-d6aa-11ed-b10e-ff3b2a9f7a5a',
       'e2aa48f0-9811-11ed-8e91-45829fd1c2b4',
       '0c70d2a0-cbf5-11ed-98eb-8fb393b43733',
       '92b57090-b139-11ed-bc50-8f526e7e063d',
       '38855b10-9dc3-11ec-a5aa-b357fe13be33',
       'a37b0d40-270e-11ee-8e44-d51a412c3f36',
       'd2d375d0-73e6-11ee-b534-4302eb3f4bab',
       'cc2e7360-f057-11ec-a3bb-efceb4f881d5',
       'e827dfb0-3c33-11ee-803a-f7dad046c8cb',
       'd5a0b610-f533-11ed-bc02-fd79a6ce904e',
       '998c6c70-3122-11ee-8d95-231254025f75',
       '4158c650-4fa1-11ee-aafb-7f475aadde23',
       '86762fd0-7949-11ee-a68c-098cfd32333b',
       'e12fec30-9e2b-11ed-a6a4-e7637bb10c1c',
       '34061640-095f-11ec-8e63-4b3c41117f08',
       '4244e850-7954-11ee-a6ba-75e6409540b3',
       '93bcc630-f369-11eb-bd9d-233c371f5df1',
       '0172d0d0-d022-11ec-add7-4d217eb6dbb3',
       'daed2f70-6dcb-11ee-a3ed-85faed8b53a2',
       '6e255e80-5ead-11ee-b9ab-514ff5ef01dc',
       '601d66a0-63b6-11ec-8a00-81f651d0b14a',
       'f0b3c160-9edf-11eb-a621-a52206b18040',
       '970333f0-01d7-11ee-ad74-31ca2502a364',
       '7ea52780-1d86-11ee-a31e-7b03cc8df464',
       '07008890-ea42-11ed-9a53-0f6e03e3ccf8',
       '1d265690-099d-11ec-8c1f-279bde56d3d4',
       '8bf6b710-13ee-11ee-a4f2-8f018c3bebbc',
       'e0490c60-586c-11ee-a032-b30bdc591644',
       '987a1860-043f-11e9-b29a-657a90787be9',
       '37e32200-948b-11ec-9695-c918fcda5fe0',
       '9ea21d90-266f-11e8-bdcc-8bfb8cd4ee41',
       '096d32c0-da9f-11ed-b047-9fdce0a5ef36',
       'b08174b0-7868-11ee-bcf9-a3842ab43b05',
       '3cff3920-7983-11ee-8605-5fedca27c7c0',
       '558a0ad0-e7ad-11ea-a29f-7bdd9372cc29',
       'd5073690-76d7-11ee-86bb-a1068cfdd602',
       '262fe3d0-35cb-11ee-bf75-5ba290ef6734',
       'e2697cd0-4e23-11ee-bd17-573b905892df',
       '191c9110-9087-11ec-ace4-d10f5b687971',
       'bc31c660-76de-11ee-b770-79a335abed02',
       '3d725710-5d16-11ec-92a5-d55bf1f546e2',
       '4865fe90-7981-11ee-b020-cb18186498d3',
       'e7fe7640-eff6-11ed-8347-35f08cecf43b',
       '95ec0810-6402-11ee-a9cb-bbca9f0a073e',
       'abcb7360-c492-11ed-903d-8f88c32aba88',
       '01218890-61af-11ee-9ed9-a9054909413e',
       '657ffd60-eeed-11ed-a3f2-95075062a87c',
       'd9503170-f27c-11eb-9dfb-4f0cd0571065',
       'e3b73680-68d2-11ee-94f8-e74144b3dd83',
       '45efb510-491d-11ed-a9f5-71ca9a1e60a5',
       '6bdbdf50-cb61-11eb-a7d2-399358e62b46',
       '8380b140-9341-11ed-9810-87420a46fe8b',
       '265b0790-1782-11ec-9cf7-41818aa3fea0',
       '5c996570-ad4c-11ed-ad4f-9748a31b1749',
       'd0e78190-561c-11ee-9604-61cab66a9198',
       '6e3654c0-02b3-11ee-b0ec-11f5491025c0',
       '321133f0-ae23-11ed-9192-2b741cf7943d',
       'cc0be1f0-76d0-11ee-924e-19f1818d9def',
       '1b719ad0-7962-11ee-b03e-f35725999f11',
       '3da30030-78f4-11ee-af85-8d886da62a36',
       'e9e87970-683b-11ee-9a01-ebe9a7ac0e13',
       '5a995e70-fdd7-11ed-af20-e9a0c0acd0e0',
       '0e0f02a0-6cb1-11ee-953b-e374d20d0ab3',
       '4c749bc0-1ac6-11ec-b507-6d3180b60d38',
       '552cc5a0-1518-11ee-8de4-d74f831ebe75',
       '4445b3a0-76de-11ee-9e07-2b21e6f1f700',
       '60355210-28de-11eb-aa02-c3649cfe7f71',
       'f7308750-2725-11ee-850a-23692e8fd68f',
       '3a55dea0-e805-11ed-806b-67209023310c',
       '51fc4970-b951-11eb-b18b-e576f0c0802a',
       '4c1ac6c0-d8ef-11ed-902b-374a18e74844',
       'd32aaed0-6c99-11ee-b1f7-c7162b278a43',
       '466328d0-a39d-11ed-bb0c-354a95447fbc',
       'a3a3e0a0-13f7-11ee-bb1c-f95ada8d9aaf',
       'fb7c8aa0-2432-11eb-9848-b586df62e7a4',
       '1e1157a0-61d7-11ee-9479-7f5f7ee96b0d',
       'adbdffd0-f5b4-11ea-9ba2-c9a2de53aa70',
       '8e78d720-b5a8-11ec-9f7f-156fc6842ce8',
       '28d24d30-e670-11ed-b58a-6315aaa007e5',
       '32576a80-a39f-11ec-a680-09fcc5f5cdba',
       'ed814c00-223c-11ee-b892-13192efe75f9',
       'b0894330-7934-11ee-9e83-b318db1f0218',
       '154ae0b0-763f-11ee-86b9-7f40407285b5',
       'd31229a0-b682-11ed-bc8f-7969950cf065',
       'e7cfe960-2d45-11ee-bfbc-3f56c4d4fed8',
       '94505710-5eec-11ee-a1a0-7329154e49fb',
       '82d27e80-448b-11ee-90cd-538c962db324',
       'dde052a0-264c-11ee-a20d-f3a1c2f94071',
       '35901350-77d7-11ea-9dd0-73baf10c8c3a',
       'f09a5ce0-ec6d-11ea-87a9-ef965f094656',
       '6863dc30-07ea-11ed-8e45-6d2618168de3',
       '8a81dbd0-760e-11ee-9110-b7a57991987e',
       '2e7c5e80-5ba8-11ee-99cd-cba75f44cf5e',
       '10923af0-10c3-11ee-9d93-c7331a233ca5',
       '62101f10-f600-11ed-a96e-3f4ed4d0abe4',
       'f4c7ad30-1a08-11ec-9895-75c0d1eb6ffe',
       '6663f4a0-08df-11ee-81cb-8be2005d9c9c',
       '31214450-2690-11e8-b8fd-0b549d32ed37',
       '2a1aa6c0-6748-11ee-934a-1548f0cbed48',
       '405db4b0-5a3a-11ee-87f2-49831b92684d',
       'ce79df20-e0fb-11ed-ae6e-e9ce17e234c0',
       '6e4ff490-7912-11ee-aab2-2be8673ecdb3',
       'fcd3b500-6e61-11ee-8a32-596792dfe63e',
       '695c5ef0-25e2-11eb-a938-6bff07fe5479',
       'c2f710e0-26f7-11e9-ba19-73f8edd5211f',
       'f57c1b00-d339-11eb-9be7-f7128e456267',
       '576dd830-3797-11ee-a08b-19577d0baed4',
       '084e6540-9804-11ed-bc94-8dd1b55f15b7',
       '84ac4220-0ed4-11ec-90ba-bf9440b194e7',
       'be0a5de0-4f3a-11eb-8acf-69d3bdfb693c',
       '2d48ad60-e878-11ec-89e6-f50bb0107659',
       '4a4b54f0-65e1-11eb-8ef4-0344a67f1f47',
       'ac25a8b0-7939-11ee-844d-c97f903509c5',
       '03f0b390-7968-11ee-ac6c-6f203073c63f',
       '246c66c0-0b2a-11ee-a875-8fcd12a907c6',

In [25]:
returned_users = set(first_day_users) & set(second_day_users)

In [26]:
returned_users

{'0172d0d0-d022-11ec-add7-4d217eb6dbb3',
 '0176d5d0-eff3-11ed-8ea5-5f4c473eaf0a',
 '036c87b0-267a-11e8-8408-f9f917206103',
 '04b60840-0f21-11ee-9f41-590a8bddb14f',
 '08ab2690-52d5-11ee-ba43-bd8cc8a1c62d',
 '0b7e3220-a8ff-11ed-ac6e-2b8b3b227614',
 '0c1031e0-e4a8-11ed-9e2b-e9731131cca2',
 '0e7a9110-4b04-11ee-95ae-474bd0bb7789',
 '0ff816e0-4ae4-11ee-b398-5b4806a4e10c',
 '119f18e0-43cd-11ee-b3c7-97dbf58e5c66',
 '11c6d7f0-6294-11ee-ba99-8303071649fa',
 '130cc240-7889-11ee-aa17-571fcadf0394',
 '154ae0b0-763f-11ee-86b9-7f40407285b5',
 '17106bb0-b3d9-11ec-8539-4f93fa6e64e3',
 '17ce4000-77db-11ee-a3a0-edfd72e146b8',
 '17e3c5e0-f2d2-11ec-9a9d-15ce92c49139',
 '18554290-dfdd-11ec-bd0b-89a07386757e',
 '1a633e20-6745-11ee-ad73-95d1cc768655',
 '1c4a5160-90e0-11ed-bb38-47496bab1f09',
 '1d265690-099d-11ec-8c1f-279bde56d3d4',
 '21a20810-76d6-11ee-8ad3-ff3e78388499',
 '2418ed40-e322-11ed-a3c3-39019ef4fa21',
 '262f13e0-7aa7-11ed-8af5-2fc8820d33f9',
 '2630a7f0-3a7d-11ee-88b2-d18fd7859087',
 '265b0790-1782-11ec-9cf7-41818aa3fea0',
 '27bcbb20-5101-11ec-891e-9b7b6489f94e',
 '289bc360-afde-11ec-a882-df5bc25920ab',
 '28a70d20-916e-11ed-b4cc-134d52c5124a',
 '29e694b0-2e97-11ed-8dc3-3742abce6e54',
 '2a1aa6c0-6748-11ee-934a-1548f0cbed48',
 '30873ef0-7875-11ed-b201-29b2b3a1b32c',
 '31214450-2690-11e8-b8fd-0b549d32ed37',
 '32576a80-a39f-11ec-a680-09fcc5f5cdba',
 '32b3ba10-33a2-11eb-8aee-8751efd2dc63',
 '33864540-382f-11ee-a5a1-cfd5c6784c6b',
 '339ebd80-6077-11ee-b58d-494ef973954d',
 '34061640-095f-11ec-8e63-4b3c41117f08',
 '345d0fb0-5cee-11ee-a031-f9e6d8874212',
 '3629cac0-721d-11ed-8fc7-4fd9990e1e38',
 '364354f0-e4d6-11ed-857b-f11dd0dac507',
 '3816d050-5e83-11ee-b787-016174f78978',
 '38855b10-9dc3-11ec-a5aa-b357fe13be33',
 '38f23a60-60d6-11ed-9055-050ecf74bb2a',
 '390074a0-6b7c-11eb-8ef9-73f675c1c29c',
 '3a5bab80-269c-11e8-8319-456ad9d3b8d8',
 '3aa5e760-d3a1-11ed-b6d4-25cf9788359e',
 '3b100450-8fc8-11ed-a4ee-39bb2f444421',
 '3c07be10-ad51-11ed-9123-7986d83596a7',
 '3d8322f0-209e-11ee-bdb7-63a16ffb097c',
 '3fad9220-6398-11ea-9789-39cafe3b86b6',
 '426c0c10-2670-11e8-952c-5397ebbba8bb',
 '429c6650-c107-11eb-919c-2b8cd2bff7e9',
 '438855d0-67d7-11eb-ba32-55dcd093b535',
 '47d1d680-b5d1-11ed-819a-7fe655647e59',
 '491848d0-0086-11ee-af2c-ab4d4b149261',
 '4b065740-f8b1-11ed-a0ea-43015548e4d6',
 '51ed0430-73b0-11ee-bf70-db2f3e338908',
 '51fc4970-b951-11eb-b18b-e576f0c0802a',
 '537ccfb0-6a5f-11ee-83f9-3d79d5a1b56e',
 '580b1600-5aeb-11ee-a31a-718c9cb74cd4',
 '5a658050-0c93-11ec-ab65-cb67d5fe8127',
 '5a92ee20-4d5d-11ee-b2b5-db70ae66610e',
 '5c996570-ad4c-11ed-ad4f-9748a31b1749',
 '60355210-28de-11eb-aa02-c3649cfe7f71',
 '616c5140-ffa8-11ec-8176-2b307e306f56',
 '62101f10-f600-11ed-a96e-3f4ed4d0abe4',
 '6261b740-7872-11ee-961f-5517ccf7abcc',
 '62bfe730-6e8a-11ee-ac29-9f6e169b060e',
 '648c2480-c0ab-11ed-9a17-8396e86aa4ff',
 '64b239c0-e33f-11ed-9e8a-0720496d6e5a',
 '65b5b460-2c46-11e8-b433-e9a46e5ade44',
 '6863dc30-07ea-11ed-8e45-6d2618168de3',
 '68871210-3b23-11ed-9944-954c1c93b64c',
 '6c901470-a611-11ed-9911-91a434dda2f6',
 '6d656ad0-24ce-11ee-98ae-69359935c18d',
 '6e255e80-5ead-11ee-b9ab-514ff5ef01dc',
 '6e3654c0-02b3-11ee-b0ec-11f5491025c0',
 '704fa250-c082-11ea-bb43-c1bfd3d804d5',
 '71aa0370-bc01-11ed-b475-112ce88e695c',
 '77d26ec0-9a8c-11ea-a2fd-3d9ff5d8d5c2',
 '7b3d2810-e585-11ed-a524-d983167b6653',
 '82aff070-57bc-11ed-a1f1-d9a024bf871f',
 '82d27e80-448b-11ee-90cd-538c962db324',
 '8313cd60-4303-11ee-b9f7-77e376310446',
 '83dc6ec0-5dec-11ed-a7f8-43cd2dca137b',
 '86576eb0-cedb-11ed-8a6f-f38a23eae62b',
 '8a45d150-cadc-11ec-91b0-45d5da48b7f1',
 '8aca5ab0-4c2d-11ed-ba4f-3339b0969613',
 '8b142ef0-0cf5-11ed-8af1-63871af601f1',
 '8c1900c0-18ff-11ee-b3c8-89750e6b01d2',
 '904969c0-5db8-11ee-9185-e5270066a2d3',
 '90626340-6717-11df-be47-03f2d32a026e',
 '942b14b0-3740-11ee-9c50-23d848797bb4',
 '97eddc80-3df6-11ec-8968-315368755a67',
 '987a1860-043f-11e9-b29a-657a90787be9',
 '9a0f4460-a9a2-11eb-be82-75b0b9b423a9',
 '9d657c50-6965-11ec-a4a9-912dae094ad1',
 '9f7b14f0-dd2a-11ea-8b48-7b8c98006cb0',
 'a12fd5c0-13d2-11ed-9577-2f98a8ff01ab',
 'a3a3e0a0-13f7-11ee-bb1c-f95ada8d9aaf',
 'a4d16cb0-140e-11ee-8f85-05a7683ba1dc',
 'a5623b20-8eb0-11ed-aabd-01b51f03cf9b',
 'a5ad2250-fb86-11ed-9389-fb3ae8cc6873',
 'af142b30-4114-11ee-a7af-95b819bc48f9',
 'afe913b0-71c0-11ec-a39a-1d0894f5a843',
 'b102e250-b46b-11ed-9e46-b1e2925e9c5c',
 'b322ea40-33ae-11ee-8975-1dbaaffcfb54',
 'b4d28780-046b-11eb-a7aa-2f3d29bb7930',
 'b8800af0-6dc8-11ee-8ada-c7d2dc4bb73d',
 'b919eba0-ca20-11eb-b368-69bb43c71b4d',
 'bafb8570-e353-11ed-9753-edccc786c976',
 'bca39490-6683-11ee-992d-69dc3ee71800',
 'bec55e60-bd4d-11ec-bad1-352a3c90f6eb',
 'bf07d300-a3e6-11ed-bcd5-cf87783ff67e',
 'bf7a2d50-5df5-11ee-832a-37e0ed135bb2',
 'bfb84fc0-b958-11eb-b3b5-714825858d67',
 'c0851320-fad8-11ed-8bb9-5793d27ec8d2',
 'c230e1c0-5ae8-11ee-b386-5de8a6c82938',
 'c26d3200-5125-11ee-9a0f-c3816d7eb1e0',
 'c305d4a0-a915-11ed-94f7-d9cc05d27ce1',
 'c43859a0-2576-11ee-95c0-f3a8eb36e260',
 'c44efdd0-2bdd-11eb-a6a8-374e84e5cb57',
 'c858e090-9098-11ed-b7e1-4120ad641f1d',
 'c8e05f30-2408-11ee-92ec-59cbbcb06bf8',
 'caa524f0-f3c9-11ed-85ac-3ddcab99fad3',
 'cbb2af70-a51a-11eb-bc9a-9b8287359b8f',
 'cbe265f0-6a64-11ee-8d8d-c1e74f246393',
 'cf733600-e3ea-11ed-a5b9-b3c6a94e0cba',
 'd0924d40-1a32-11ee-b6e7-dd1694746746',
 'd234f070-2821-11ed-9ce0-b7a9dd423e66',
 'd31229a0-b682-11ed-bc8f-7969950cf065',
 'd3b12610-305f-11ea-82bc-2b8c7401f0aa',
 'd4021a30-2fd1-11eb-a413-8d939cea62b3',
 'd4634e60-c2e5-11ec-8d98-55a7b6fe357d',
 'd70dcaa0-0d9b-11ec-9480-19aec6605e49',
 'd78fa1e0-6ef9-11ed-886e-31f3a6be4046',
 'd9019820-62bf-11ee-8b61-21253dd65b02',
 'd94e80e0-44c9-11ee-bd5d-df6656db5b76',
 'd98ef990-d454-11ec-b3f4-8913374e2678',
 'dc644e90-d6fb-11ed-ba63-c7c8945732db',
 'ddef2360-3147-11ee-9b78-edbe9e3bbef3',
 'ded85690-6f2f-11ee-90dc-d3739fe86b1a',
 'e00bbcd0-2c9c-11ee-87a7-3f33b7dd19dd',
 'e247acc0-1c7a-11ee-bda5-8961e2ebcb05',
 'e2c41360-af2e-11ec-a79f-33c5a6212867',
 'e2f4e540-7475-11ee-9392-217b8bd22c9e',
 'e64e9970-106a-11ea-a81f-2d486e26c435',
 'e7cfe960-2d45-11ee-bfbc-3f56c4d4fed8',
 'e94b3f20-6345-11ee-9b1b-7985eb1a6cef',
 'e95d9380-75ad-11ee-9778-df20dfde0e14',
 'e9820b90-6a61-11ee-abcc-dd75dcdd7e70',
 'ea6d81d0-78ab-11ee-aac8-61ef4ba0b1e5',
 'ecdd4bc0-2edd-11ee-8089-99f61dbe7a4d',
 'ee4fd9c0-b57e-11ec-8ef1-e763c87d7838',
 'f09a5ce0-ec6d-11ea-87a9-ef965f094656',
 'f21e22d0-567f-11ed-ab53-0db2be12f6a3',
 'f3b05090-6386-11ee-b738-411998dddbba',
 'f5c917b0-19f6-11ee-9ff9-bb2aeb994a1d',
 'f65363c0-0724-11ec-bd81-49e1f86f6eaa',
 'f67af260-7747-11ee-95b1-c90f48d8dcba',
 'f7c16bf0-448d-11ee-9152-5d2cf8d23c8d',
 'fc825680-6275-11ee-a126-ff40476b8939',
 'fd5c08a0-614c-11ee-9ce0-e14fc61820da',
 'fe52f2d0-7152-11ee-ba94-f78c26841e52',
 'ff847860-b685-11ec-988b-f7bc901f6613',
 'fffec340-4ae0-11ee-aa64-cb452c798cf7'}

In [27]:
retention = len(returned_users) / len(first_day_users)

In [29]:
round(retention*100,2)

26.65

In [44]:
#5
conversion = (df.groupby('user_id')['view_adverts'].sum() > 0).mean()
round(conversion*100,1)

np.float64(46.3)

In [40]:
#6
avg_adv = df.groupby('user_id')['view_adverts'].sum().mean()

In [45]:
avg_adv

np.float64(2.8687000916350307)

In [49]:
#7
detractors = 500
promoters = 1200
passives = 300
total=detractors+promoters+passives
nps = (promoters - detractors)*100/total
nps

35.0

In [51]:
#8
import pandas as pd
from scipy.stats import ttest_ind

df = pd.read_excel('Данные для тестового задания.xlsx', sheet_name=1)
results = []

for exp in df['experiment_num'].unique():
    sub = df[df['experiment_num'] == exp]
    
    control = sub[sub['experiment_group'] == 'control']['revenue']
    test = sub[sub['experiment_group'] == 'test']['revenue']
    
    control_arpu = control.mean()
    test_arpu = test.mean()
    
    t_stat, p_value = ttest_ind(test, control, equal_var=False)
    
    uplift = (test_arpu - control_arpu) / control_arpu * 100
    
    results.append([
        exp,
        control_arpu,
        test_arpu,
        uplift,
        p_value
    ])

pd.DataFrame(results, columns=[
    "experiment_num",
    "control_arpu",
    "test_arpu",
    "uplift_%",
    "p_value"
])

   experiment_num  control_arpu   test_arpu   uplift_%   p_value
0               1    722.460215  665.739583  -7.851039  0.688966
1               2    704.653763  332.929167 -52.752801  0.001128
2               3    663.206452  998.668750  50.581881  0.060315

In [9]:
#9
df1 = pd.read_excel('Данные для тестового задания.xlsx', sheet_name=2)

In [10]:
df1

     user_id       date  cnt_adverts  age  cnt_contacts  revenue
0        100 2022-01-01            6   21           119       53
1        100 2022-01-02            2   21           200       18
2        100 2022-01-03            6   21           193       42
3        100 2022-01-04            2   21           143       38
4        100 2022-01-05            2   21           190       40
..       ...        ...          ...  ...           ...      ...
153      130 2022-01-27            1   22           185       60
154      130 2022-01-19            0   22            86       41
155      130 2022-01-28            0   22           183        5
156      130 2022-01-30            0   22            86       12
157      130 2022-01-13            2   22            97       27

[158 rows x 6 columns]

In [11]:
arpu = df1['revenue'].sum() / df1['user_id'].nunique()

In [12]:
arpu

np.float64(156.48387096774192)

In [22]:
#10
df1.groupby('user_id')['age'].first().mean()

np.float64(27.93548387096774)

In [23]:
#18
from statsmodels.stats.proportion import proportions_ztest

successes = [1003, 1099]  
samples = [100047501, 100001055] 

stat, p_value = proportions_ztest(successes, samples)

cr_a = successes[0] / samples[0]
cr_b = successes[1] / samples[1]

uplift = (cr_b - cr_a) / cr_a * 100

print("CR A:", cr_a)
print("CR B:", cr_b)
print("Uplift %:", uplift)
print("p-value:", p_value)

CR A: 1.0025237911739544e-05
CR B: 1.0989884056723202e-05
Uplift %: 9.622177084237158
p-value: 0.03533044544854254

In [24]:
if p_value < 0.05:
    if cr_b > cr_a:
        print("Вывод: B статистически значимо лучше → внедряем")
    else:
        print("Вывод: B статистически значимо хуже → не внедряем")
else:
    print("Вывод: нет статистически значимого различия")

Вывод: B статистически значимо лучше → внедряем